import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../Components/navbar/Navbar';
import Footer from '@/Components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })
// const Outfit = Outfit({
//    subsets: ['latin'],
//     weight: '400'
//   })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
